---
title: "WB Financial Heuristic Endline survey"
author: ""

date: "JUNE 20, 2024"

output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    
    
---


```{r setup, include=FALSE}
library(flexdashboard)
library(haven)
library(plyr)
library(tidyverse)
library(dplyr)
library(lubridate)
library(highcharter)
library(plotly)
library(DT)
library(stringr)
library(ggplot2)
library(viridis)
library(hrbrthemes)
```

```{r}
data <-read_dta("C:/Projects/CTO/WB Financial heuristic survey/Dashboard/WB_Financial_Heuristic_Endline_survey_Final.dta")

data <- as_factor(data)

data$SubmissionDate <- as_date(data$SubmissionDate)
data <- data %>% dplyr::rename("Date_of_interview" = "SubmissionDate")

data <- data %>% dplyr::rename("city" = "s1_10")
data <- data %>% dplyr::rename("Age" = "s1_6")

data <- data %>% dplyr::rename("HH_MEMEBER" = "s3_1")

data <- data %>% 
  mutate(
    enum_name = str_replace(enum_name,"Abrehet Wolday", "Abrehet"), 
    enum_name = str_replace(enum_name,"Addis Worku", "Addis"), 
    enum_name = str_replace(enum_name,"Alemitu Amanuel", "Alemitu"), 
    enum_name = str_replace(enum_name,"Anteneh Zerihun", "Anteneh"), 
    enum_name = str_replace(enum_name,"Ashenafi Keramo", "Ashenafi"), 
    enum_name = str_replace(enum_name,"Berhan Wangoro", "Berhan"), 
    enum_name = str_replace(enum_name,"Biniyam Desta", "Biniyam"), 
    enum_name = str_replace(enum_name,"Biruktawit Mulugeta", "Biruktawit"), 
    enum_name = str_replace(enum_name,"Bisrat Yeneneh", "Bisrat"), 
    enum_name = str_replace(enum_name,"Bitaniya Meku", "Bitaniya"), 
    enum_name = str_replace(enum_name,"Eldana Gobeze", "Eldana"), 
    enum_name = str_replace(enum_name,"Elem Lemma", "Elem"), 
    enum_name = str_replace(enum_name,"Elilta Elias", "Elilta"), 
    enum_name = str_replace(enum_name,"Endalew Gadisa", "Endalew"), 
    enum_name = str_replace(enum_name,"Etenesh Mulugeta", "Etenesh_M"), 
    enum_name = str_replace(enum_name,"Etenesh Zenebe", "Etenesh_Z"), 
    enum_name = str_replace(enum_name,"Exon Mohammed", "Exon"), 
    enum_name = str_replace(enum_name,"Eyerusalem Halefom", "Eyerusalem"), 
    enum_name = str_replace(enum_name,"Fikadu Thomas", "Fikadu"), 
    enum_name = str_replace(enum_name,"Frehiwt Mesfin", "Frehiwt"), 
    enum_name = str_replace(enum_name,"Genet Belay", "Genet"), 
    enum_name = str_replace(enum_name,"Habtewold Mekonne", "Habtewold"), 
    enum_name = str_replace(enum_name,"Hawi Legesse", "Hawi"), 
    enum_name = str_replace(enum_name,"Helen Tesfaye", "Helen"), 
    enum_name = str_replace(enum_name,"Hiwot Endeg", "Hiwot"), 
    enum_name = str_replace(enum_name,"Ikram Mohammed", "Ikram"), 
    enum_name = str_replace(enum_name,"Kdan Hailu", "Kdan"), 
    enum_name = str_replace(enum_name,"Kebede Lemmessa", "Kebede"), 
    enum_name = str_replace(enum_name,"Kokeb kahssay", "Kokeb"), 
    enum_name = str_replace(enum_name,"Meaza G/Meskel", "Meaza"), 
    enum_name = str_replace(enum_name,"Mesert Desalegn", "Mesert"), 
    enum_name = str_replace(enum_name,"Mhiretu Derebe", "Mhiretu"), 
    enum_name = str_replace(enum_name,"Muluembet Ejigu", "Muluembet"), 
    enum_name = str_replace(enum_name,"Nastanet Tolera", "Nastanet"), 
    enum_name = str_replace(enum_name,"Robel Asefa", "Robel"), 
    enum_name = str_replace(enum_name,"Samrawit Tegegn", "Samrawit"), 
    enum_name = str_replace(enum_name,"Seble Solomon", "Seble"), 
    enum_name = str_replace(enum_name,"Semegn Abebe", "Semegn"), 
    enum_name = str_replace(enum_name,"Senait Diriba", "Senait"), 
    enum_name = str_replace(enum_name,"Senayt Alemu", "Senayt"), 
    enum_name = str_replace(enum_name,"Shewazewud Birhanu", "Shewazewud"), 
    enum_name = str_replace(enum_name,"Sisaynesh Alemayehu", "Sisaynesh"), 
    enum_name = str_replace(enum_name,"Solomon Teferi", "Solomon"), 
    enum_name = str_replace(enum_name,"Surafel Mekibib", "Surafel"), 
    enum_name = str_replace(enum_name,"Tadelu Dejene", "Tadelu"), 
    enum_name = str_replace(enum_name,"Tejnat Geta", "Tejnat"), 
    enum_name = str_replace(enum_name,"Tesfanesh Assefa", "Tesfanesh"), 
    enum_name = str_replace(enum_name,"Tigist Melku", "Tigist"), 
    enum_name = str_replace(enum_name,"Yeabsira Ayele", "Yeabsira"), 
    enum_name = str_replace(enum_name,"Zufan Gebreyesus", "Zufan"), 

  )


```

HOME
=====================================
Row
-----------------------------------------------------------------------


### TOTAL SYNCED

```{r}
total_interview<-nrow(data)
valueBox(total_interview, icon = "fa-bar-chart")
```


## Column

### NO. OF INTERVIEWS BY ENUMERATOR {data-width="600"}

```{r Endline}
Abrehet <- data %>% filter(enum_name == "Abrehet") %>% nrow()
Addis <- data %>% filter(enum_name == "Addis") %>% nrow()
Alemitu <- data %>% filter(enum_name == "Alemitu") %>% nrow()
Anteneh <- data %>% filter(enum_name == "Anteneh") %>% nrow()
Ashenafi <- data %>% filter(enum_name == "Ashenafi") %>% nrow()
Berhan <- data %>% filter(enum_name == "Berhan") %>% nrow()
Biniyam <- data %>% filter(enum_name == "Biniyam") %>% nrow()
Biruktawit <- data %>% filter(enum_name == "Biruktawit") %>% nrow()
Bisrat <- data %>% filter(enum_name == "Bisrat") %>% nrow()
Bitaniya <- data %>% filter(enum_name == "Bitaniya") %>% nrow()
Eldana <- data %>% filter(enum_name == "Eldana") %>% nrow()
Elem <- data %>% filter(enum_name == "Elem") %>% nrow()
Elilta <- data %>% filter(enum_name == "Elilta") %>% nrow()
Endalew <- data %>% filter(enum_name == "Endalew") %>% nrow()
Etenesh_M <- data %>% filter(enum_name == "Etenesh_M") %>% nrow()
Etenesh_Z <- data %>% filter(enum_name == "Etenesh_Z") %>% nrow()
Exon <- data %>% filter(enum_name == "Exon") %>% nrow()
Eyerusalem <- data %>% filter(enum_name == "Eyerusalem") %>% nrow()
Fikadu <- data %>% filter(enum_name == "Fikadu") %>% nrow()
Frehiwt <- data %>% filter(enum_name == "Frehiwt") %>% nrow()
Genet <- data %>% filter(enum_name == "Genet") %>% nrow()
Habtewold <- data %>% filter(enum_name == "Habtewold") %>% nrow()
Hawi <- data %>% filter(enum_name == "Hawi") %>% nrow()
Helen <- data %>% filter(enum_name == "Helen") %>% nrow()
Hiwot <- data %>% filter(enum_name == "Hiwot") %>% nrow()
Ikram <- data %>% filter(enum_name == "Ikram") %>% nrow()
Kdan <- data %>% filter(enum_name == "Kdan") %>% nrow()
Kebede <- data %>% filter(enum_name == "Kebede") %>% nrow()
Kokeb <- data %>% filter(enum_name == "Kokeb") %>% nrow()
Meaza <- data %>% filter(enum_name == "Meaza") %>% nrow()
Mesert <- data %>% filter(enum_name == "Mesert") %>% nrow()
Mhiretu <- data %>% filter(enum_name == "Mhiretu") %>% nrow()
Muluembet <- data %>% filter(enum_name == "Muluembet") %>% nrow()
Nastanet <- data %>% filter(enum_name == "Nastanet") %>% nrow()
Robel <- data %>% filter(enum_name == "Robel") %>% nrow()
Samrawit <- data %>% filter(enum_name == "Samrawit") %>% nrow()
Seble <- data %>% filter(enum_name == "Seble") %>% nrow()
Semegn <- data %>% filter(enum_name == "Semegn") %>% nrow()
Senait <- data %>% filter(enum_name == "Senait") %>% nrow()
Senayt <- data %>% filter(enum_name == "Senayt") %>% nrow()
Shewazewud <- data %>% filter(enum_name == "Shewazewud") %>% nrow()
Sisaynesh <- data %>% filter(enum_name == "Sisaynesh") %>% nrow()
Solomon <- data %>% filter(enum_name == "Solomon") %>% nrow()
Surafel <- data %>% filter(enum_name == "Surafel") %>% nrow()
Tadelu <- data %>% filter(enum_name == "Tadelu") %>% nrow()
Tejnat <- data %>% filter(enum_name == "Tejnat") %>% nrow()
Tesfanesh <- data %>% filter(enum_name == "Tesfanesh") %>% nrow()
Tigist <- data %>% filter(enum_name == "Tigist") %>% nrow()
Yeabsira <- data %>% filter(enum_name == "Yeabsira") %>% nrow()
Zufan <- data %>% filter(enum_name == "Zufan") %>% nrow()

```

```{r}

sup_name <- c("Abrehet", 	"Addis", 	"Alemitu", 	"Anteneh", 	"Ashenafi", 	"Berhan", 	"Biniyam", 	"Biruktawit", 	"Bisrat", 	"Bitaniya", 	"Eldana", 	"Elem", 	"Elilta", 	"Endalew", 	"Etenesh_M", 	"Etenesh_Z", 	"Exon", 	"Eyerusalem", 	"Fikadu", 	"Frehiwt", 	"Genet", 	"Habtewold", 	"Hawi", 	"Helen", 	"Hiwot", 	"Ikram", 	"Kdan", 	"Kebede", 	"Kokeb", 	"Meaza", 	"Mesert", 	"Mhiretu", 	"Muluembet", 	"Nastanet", 	"Robel", 	"Samrawit", 	"Seble", 	"Semegn", 	"Senait", 	"Senayt", 	"Shewazewud", 	"Sisaynesh", 	"Solomon", 	"Surafel", 	"Tadelu", 	"Tejnat", 	"Tesfanesh", 	"Tigist", 	"Yeabsira", 	"Zufan")

sup_count <- c(Abrehet, 	Addis, 	Alemitu, 	Anteneh, 	Ashenafi, 	Berhan, 	Biniyam, 	Biruktawit, 	Bisrat, 	Bitaniya, 	Eldana, 	Elem, 	Elilta, 	Endalew, 	Etenesh_M, 	Etenesh_Z, 	Exon, 	Eyerusalem, 	Fikadu, 	Frehiwt, 	Genet, 	Habtewold, 	Hawi, 	Helen, 	Hiwot, 	Ikram, 	Kdan, 	Kebede, 	Kokeb, 	Meaza, 	Mesert, 	Mhiretu, 	Muluembet, 	Nastanet, 	Robel, 	Samrawit, 	Seble, 	Semegn, 	Senait, 	Senayt, 	Shewazewud, 	Sisaynesh, 	Solomon, 	Surafel, 	Tadelu, 	Tejnat, 	Tesfanesh, 	Tigist, 	Yeabsira, 	Zufan
)

sup_data <- data.frame(sup_name, sup_count)
sup_data <- sup_data %>% arrange(sup_count)

#to arrange
sup_data$sup_name<- factor(sup_data$sup_name, levels=sup_data[["sup_name"]])

#plot fig
fig1 <- sup_data %>% plot_ly()
fig1 <- fig1 %>% add_trace(x = ~sup_name, y = ~sup_count, type = 'bar',  name = 'Household data', marker = list(color = '#006E7F'))

fig1 <- fig1 %>% layout(xaxis = list(title = ''), barmode = 'group')          
fig1 <- fig1 %>% layout(yaxis = list(title = 'n'), barmode = 'group')

fig1


```

### NO. OF INTERVIEWS  BY REGION {data-width=300}

```{r }
data %>% 
  dplyr::count(region) %>%
  arrange(-n) %>% 
  hchart('bar', hcaes(x = 'region', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```


### NO. OF INTERVIEWS  BY CITY {data-width=300}

```{r }
data %>% 
  dplyr::count(city) %>%
  arrange(-n) %>% 
  hchart('pie', hcaes(x = 'city', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```

Column 
-----------------------------------------------------------------------
### NO. OF INTERVIEWS DONE BY DATE {data-width=400}

```{r }
data %>% 
  dplyr::count(starttime) %>%
  arrange(-n) %>% 
  hchart('line', hcaes(x = 'starttime', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```


### RESPONDENTS BY AGE {data-width=400}

```{r }
data %>% 
  dplyr::count(Age) %>%
  arrange(-n) %>% 
  hchart('scatter', hcaes(x = 'Age', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```


### RESPONDENTS BY BY NUMBER OF HOUSEHOLD MEMBERS {data-width=400}

```{r }
data %>% 
  dplyr::count(HH_MEMEBER) %>%
  arrange(-n) %>% 
  hchart('column', hcaes(x = 'HH_MEMEBER', y = 'n'), color_stops(n=4, colors = c("#F65A83", "#FF1E00", "#21E1E1", "#224B0C")))
```